spring:
  application:
    name: wiki-producer
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8006/configServer
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,locqalhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
        
        
server:
  port: 8082
eureka:
  instance:
    hostname: localhost